import scripts.parse_nrlist

configfile: "config/config.yaml"

# Prepare a list of strings where each string includes the equivalence class name, PDB ID, and chain info for the
# equivalence class members.
eq_class_members = scripts.parse_nrlist.parse_nrlist(config["rep_set_file"], config["all_members"])

rule all:
    input:
        "data/analysis/atom_pairs.csv",
        "data/analysis/counts.csv"

rule collect_data:
    output:
        data = "data/collect_data/{eq_class_member}.csv"
    log:
        stdout = "misc/logs/collect_data/{eq_class_member}.stdout",
        stderr = "misc/logs/collect_data/{eq_class_member}.stderr"
    conda:
        "envs/general.yaml"
    script:
        "scripts/collect_data.py"

rule analyze_data:
    input:
        data = expand("data/collect_data/{eq_class_member}.csv", eq_class_member=eq_class_members)
    output:
        atom_pairs = "data/analysis/atom_pairs.csv",
        counts = "data/analysis/counts.csv"
    log:
        stdout = "misc/logs/analyze_data/output.stdout",
        stderr = "misc/logs/analyze_data/error.stderr"
    conda:
        "envs/general.yaml"
    script:
        "scripts/analyze_data.py"
